mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', TemplateView.as_view(template_name="index.html")),
    path('', include('scheduleadvisor.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

scheduleadvisor/urls.py
from django.urls import path

from . import views

app_name = 'scheduleadvisor'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('studentindex', views.studentView, name='student'),
    path('studentindex/clearnotifs', views.clear_notifs, name="clear_notifs"),
    path('advisorindex', views.advisorView, name='advisor'),
    path('advisorindex/approveschedule/<int:pk>', views.approve_schedule, name='approve_schedule'),
    path('advisorindex/rejectschedule/<int:pk>', views.reject_schedule, name='reject_schedule'),
    path('approved', views.approvedView, name='approved'),
    path('rejected', views.rejectedView, name='rejected'),
    path('search', views.searchView, name='search'),
    path('schedules/', views.scheduleView, name='schedules'),
    path('schedules/submitschedule/<int:pk>', views.submit_schedule, name='submit_schedule'),
    path('schedules/createschedule', views.create_schedule, name='create_schedule'),
    path('schedules/deleteschedule/<int:pk>', views.delete_schedule, name='delete_schedule'),
    path('schedules/editschedule/<int:pk>', views.edit_schedule, name='edit_schedule'),
    path('schedules/exportschedule/<int:pk>', views.export_schedule, name='export_schedule'),
    path('schedules/filterschedules', views.filter_schedules, name='filter_schedules'),
    path('schedules/cancelschedulesubmission/<int:pk>', views.cancel_schedule_submission, name="cancel_schedule_submission"),
    path('schedules/enroll/<int:pk>', views.enroll, name='enroll'),
    path('schedules/disenroll/<int:pk>', views.disenroll, name='disenroll'),
    path('schedules/buttontodetails/<int:pk>', views.button_to_details, name='button_to_details'),
    path('schedulebuilder/<int:pk>', views.scheduleBuilderView, name='schedulebuilder'),
    path('schedulebuilder/<int:pk>/addcoursetoschedule', views.add_course_to_schedule, name="add_course_to_schedule"),
    path('schedulebuilder/<int:pk>/deletecoursetoschedule', views.delete_course_from_schedule, name="delete_course_from_schedule"),
    path('schedulerbuilder/buttontoschedules', views.button_to_schedules, name='button_to_schedules'),
    path('cart', views.cartView, name='cart'),
    path('studentindex/addtocart', views.add_course_to_cart, name='add_course_to_cart'),
    path('cart/deletefromcart', views.delete_course_from_cart, name='delete_course_from_cart'),
    path('scheduledetails/<int:pk>', views.scheduleDetailsView, name="schedule_details_view"),
    path('advisees', views.adviseesListView, name="advisees_list_view"),
    path('advisees/addadvisee/<int:pk>', views.add_student_as_advisee, name="add_student_as_advisee"),
    path('notauthorized', views.notAuthorized, name="not_authorized")
]

scheduleadvisor/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User

from django.views import generic

from .models import Student, Advisor, SearchCourse, Schedule, ScheduleCourse, CartCourse, Cart, Notification

from ics import Calendar, Event
from dateutil.rrule import rrule, WEEKLY

import json, requests


"""

citations

removing default login messages https://stackoverflow.com/questions/25744425/how-to-clean-up-django-login-message-from-framework

bootstrap getbootstrap.com/docs/5.0

cart / javascript https://www.youtube.com/watch?v=woORrr3QNh8&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=3

sorting by datetime https://stackoverflow.com/questions/5055812/sort-python-list-of-objects-by-date


"""

def studentView(request):
    if not request.user.groups.filter(name='Student').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    
    student = Student.objects.get(user = request.user)
    notifications = Notification.objects.filter(student=student).order_by('-pub_date')

    if student.advisor == None:
        no_advisor = True
    else:
        no_advisor = False
        
    context = {
        'student': student,
        'notifications': notifications,
        'no_advisor': no_advisor
    }
    return render(request, 'scheduleadvisor/studentindex.html', context)
    

def approvedView(request):
    if not request.user.groups.filter(name='Advisor').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    advisor = request.user.advisor
    students = advisor.student_set.all()
    approved_schedules = []
    for student in students:
        try:
            #all of the approved schedules of this student
            student_approved_schedules = Schedule.objects.filter(student=student, status="Approved")
            #rejected_schedule is looping through the rejected Schedule objects of the student
            #reformatting it into schedule which is the list of lists 
            #then append schedule to rejected_schedules which is list of all rejected schedules to pass to template
            if student_approved_schedules:
                for approved_schedule in student_approved_schedules:
                    # format of rejected_schedules is list of lists
                    # each list is made up of schedulecourses that belong to that student's rejected schedule
                    schedule = []
                    for course in approved_schedule.schedulecourse_set.all():
                        schedule.append(course)
                    approved_schedules.append(schedule)  
        except Schedule.DoesNotExist:
            continue

    context = {
        'students': students,
        'approvedschedules': approved_schedules
    }
    return render(request, 'scheduleadvisor/approved.html', context)

def rejectedView(request):
    if not request.user.groups.filter(name='Advisor').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    advisor = request.user.advisor
    students = advisor.student_set.all()
    rejected_schedules = []
    for student in students:
        #all of the rejected schedules of this student
        student_rejected_schedules = Schedule.objects.filter(student=student, status="Rejected")
        #if student_rejected_schedules queryset is not empty
        if student_rejected_schedules:
            #rejected_schedule is looping through the rejected Schedule objects of the student
            #reformatting it into schedule which is the list of lists 
            #then append schedule to rejected_schedules which is list of all rejected schedules to pass to template
            for rejected_schedule in student_rejected_schedules:
                # format of rejected_schedules is list of lists
                # each list is made up of schedulecourses that belong to that student's rejected schedule
                schedule = []
                for course in rejected_schedule.schedulecourse_set.all():
                    schedule.append(course)
                rejected_schedules.append(schedule)

    context = {
        'students': students,
        'rejectedschedules': rejected_schedules
    }
    return render(request, 'scheduleadvisor/rejected.html', context)

def approve_schedule(request, pk):
    if not request.user.groups.filter(name='Advisor').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    try: 
        schedule = Schedule.objects.get(id=pk)
    except Schedule.DoesNotExist:
        return HttpResponseRedirect(reverse('scheduleadvisor:advisor'))

    if schedule.student.advisor != request.user.advisor:
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))

    schedule.status = "Approved"
    schedule.save()
    notif = Notification(
        student = schedule.student,
        schedule = schedule,
        notif = "Schedule " + schedule.title + " has been approved.",
        pub_date = timezone.now()
    )
    notif.save()
    return HttpResponseRedirect(reverse('scheduleadvisor:advisor'))

def reject_schedule(request, pk):
    if not request.user.groups.filter(name='Advisor').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    
    try: 
        schedule = Schedule.objects.get(id=pk)
    except Schedule.DoesNotExist:
        return HttpResponseRedirect(reverse('scheduleadvisor:advisor'))

    if schedule.student.advisor != request.user.advisor:
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    
    schedule.status = "Rejected"
    #schedule.comment =
    schedule.save()
    notif = Notification(
        student = schedule.student,
        schedule = schedule,
        notif = "Schedule " + schedule.title + " has been rejected.",
        pub_date = timezone.now()
    )
    notif.save()
    return HttpResponseRedirect(reverse('scheduleadvisor:advisor'))

def advisorView(request):
    if not request.user.groups.filter(name='Advisor').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    advisor = request.user.advisor
    students = advisor.student_set.all()
    submitted_schedules = []
    for student in students:
        try:
            #if the student has a schedule that's pending approval, then add that to the submitted schedules list
            submitted_schedule = Schedule.objects.get(student=student, status="Pending Approval")
            # format of submitted_schedules is list of lists
            # each list is made up of schedulecourses that belong to that student's submitted schedule
            schedule = []
            for course in submitted_schedule.schedulecourse_set.all():
                schedule.append(course)
            submitted_schedules.append(schedule)           
        except Schedule.DoesNotExist:
            continue
    context = {
        'students': students,
        'submitted_schedules': submitted_schedules
    }
    return render(request, 'scheduleadvisor/advisorindex.html', context)

def indexView(request):
    if request.user.is_authenticated:
        if request.user.groups.filter(name='Student').exists():
            try:
                student = Student.objects.get(user=request.user)
            except Student.DoesNotExist:
                student = Student.objects.create(user=request.user, stud_name=request.user.get_full_name(), username=request.user.get_username(), email=request.user.email, advisor=None)
                cart = Cart.objects.create(student=student)
            return HttpResponseRedirect(reverse('scheduleadvisor:student'))
        if request.user.groups.filter(name='Advisor').exists():
            try:
                advisor = Advisor.objects.get(user=request.user)
            except Advisor.DoesNotExist:
                advisor = Advisor.objects.create(user=request.user, adv_name=request.user.get_full_name(), username=request.user.get_username(), email=request.user.email)
            return HttpResponseRedirect(reverse('scheduleadvisor:advisor'))
        else:
            return render(request, 'scheduleadvisor/assigntogroup.html')
    else:
        return render(request, '../templates/index.html')

def searchView(request):
    if not request.user.groups.filter(name='Student').exists():
        return HttpResponseRedirect(reverse('scheduleadvisor:not_authorized'))
    #if search button was clicked
    if request.method == "POST":
        #inputs from the searching filtering form
        #term = request.POST['term_text']
        subject = request.POST['subject_text']
        catalog_number = request.POST['catalog_number_text']
        keyword = request.POST['keyword_text']
        enrollment_status = request.POST.getlist('enrollment_status')

        if (subject=="") and (catalog_number=="") and (keyword == ""):
            messages.error(request, "Fill out at least one of the search criteria.")
            return HttpResponseRedirect(reverse('scheduleadvisor:search'))

        #default api link
        api_link = "https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01"
        #add term to api link - default to fall 2023 
        api_link += "&term=1238" 
        #add subject to api link
        if subject != "":
            api_link += "&subject=" + subject.upper()
        #add catalog number to api link
        if catalog_number != "":
            api_link += "&catalog_nbr=" + catalog_number
        #add keyword to link
        if keyword != "":
            api_link += "&keyword=" + keyword
        #add enrollment status to link
        if len(enrollment_status) == 1:

scheduleadvisor/templates/scheduleadvisor/advisorindex.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


<link rel="stylesheet" type="text/css" href="{% static 'scheduleadvisor/style.css' %}">

<html>
<body>

    <div class="page">

        <div class="sidenav">
            <p>Schedule Advisor</p>
            <a href="advisorindex">Awaiting Schedules</a>
            <a href="/approved">Approved Schedules</a>
            <a href="/rejected">Rejected Schedules</a>
            <a href="/advisees">Advisees</a>
            <a href="/logout">Logout</a>
        </div>

    <!--
    Table view for Advisor. Displays Student Name, Credits in schedule
    Last column displays ability for advisor to accept or reject a schedule
    When rejected is clicked, advisor will be prompted to comment on why. Comment will be sent to student view
    When button is clicked, schedule will disappear from table
    -->
    <div class="container w-75 my-4">
        <h4 class="text-center"><u>Awaiting Schedules</u></h4>
        {% if submitted_schedules %}
            <div class="schedTable container shadow-sm border bg-light">
                <table class="mx-auto">
                <tr>
                    <th>Student Name</th>
                    <th>Schedule</th>
                    <th>Credits in Schedule</th>
                    <th>Status</th>
                </tr>

                {% for schedule in submitted_schedules %}
                    
                <tr>
                    
                    <!-- schedule refers to the first schedule (in the form of a list of ScheduleCourses) in the submitted schedules list  -->
                    <!-- schedule.0 refers to the first ScheduleCourse in the list of ScheduleCourses -->
                    <!-- student.0.schedule.student is student username -->
                    <td>{{ schedule.0.schedule.student }}</td>
                    <!-- button to click on to show the student's schedule -->
                    <td>
                        
                        <div class="col-1 text-center">
                            
                            <button type="button" class="btn btn-primary mx-auto" data-bs-toggle="modal" data-bs-target="#modal{{ schedule.0.schedule.id }}">Schedule</button>
                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="modal{{ schedule.0.schedule.id }}">
                                <div class="modal-dialog modal-xl">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <div><h5>Student: {{ schedule.0.schedule.student }}</h5></div>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                        </div>
                                        
                                        <!-- the courses  -->
                                        {% for course in schedule %}
                                        <div class="my-3">
                                            <div>
                                                <b>{{ course }}</b>
                                            </div>
                                            <div>
                                                {% if course.title != "" %}
                                                    {{ course.title }}
                                                {% endif %}
                                            </div>
                                            <div>
                                                {% if course.topic != "" %}
                                                    {{ course.topic }}
                                                {% endif %}
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <!-- credits  -->
                    <td id="sentSchedule">{{schedule.0.schedule.credits}}</td>
                    <td>
                        <form action="{% url 'scheduleadvisor:approve_schedule' schedule.0.schedule.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success mx-auto" onclick="alert('Schedule approved')">Approve</button>
                        </form>
                        <form action="{% url 'scheduleadvisor:reject_schedule' schedule.0.schedule.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger mx-auto" onclick="alert('Schedule rejected')">Reject</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="container text-center shadow-sm border bg-light">
                You have no schedules pending approval.
            </div>
        {% endif %}
    </div>
    
    </div>
</body>
</html>

<script>
var rejected;
function promptMe() {
    rejected = prompt("Provide reasoning for rejection.");
    if (rejected == null || rejected == "null" || rejected == "") {
        alert ('Cancelled');
        return;
    }
    alert ('Schedule Rejected');
    localStorage.setItem('reason', rejected);
}

function getSchedule() {
    document.getElementById("sentSchedule").innerHTML = localStorage.getItem('schedule')
}

</script>
</script>

<style>
header {
    width: 100%;
    text-align:left;
    padding: 5px 5px 10px 5px;
    margin-left: 160px; /* Same as the width of the sidenav */
}

.schedTable {
    border-collapse: collapse;
    margin-left: auto;
    margin-right: auto;
}

th, td {
  padding: 15px;
  border-bottom: 1px solid #ddd;
  border: 1px solid #ddd;
  text-align: center;
}

th {
    background-color:gray;
}


tr:nth-child(even) {background-color: #f2f2f2;}

button {
    border: none;
    padding: 5px 5px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}


.sidenav {
    height: 100%;
    width: 160px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #123C69;
    overflow-x: hidden;
    padding-top: 20px;;
}

.sidenav a {
    padding: 16px 10px 10px 16px;
    text-align:center;
    text-decoration:none;
    font-size: 17px;
    color: white;
    display: block;
}

.sidenav p {
    padding: 16px 10px 10px 16px;
    text-align:center;
    text-decoration:none;
    font-size: 25px;
    color: white;
    display: block;
}

.sidenav a:hover {
  color: blue;
}

.page {
  margin-left: 160px; /* Same as the width of the sidenav */
  padding: 10px 10px 10px 30px;

}


</style>

scheduleadvisor/templates/scheduleadvisor/assigntogroup.html
<!DOCTYPE html>

{% load socialaccount %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<link rel="stylesheet" href="{% static 'scheduleadvisor/style.css' %}">

<html>
    <div class="container text-center bg-white my-5 mx-auto">
        <p>Sign in as admin and assign user to group.</p>
        <p><a class="btn btn-primary" href="/admin">Admin Login</a></p>
        <p><a class="btn btn-primary" href="/logout">Logout</a></p>
    </div>

</html>

scheduleadvisor/templates/scheduleadvisor/cart.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!--  

    Citations

    javascript cart button https://www.youtube.com/watch?v=woORrr3QNh8&list=PL-51WBLyFTg0omnamUjL1TCVov7yDTRng&index=3


-->

<html>
    <head>
        <link rel ="stylesheet" href = "{% static 'scheduleadvisor/style.css' %}">
        <nav class="navbar navbar-expand-lg">
            <a class="px-4 navbar-brand">Schedule Advisor</a>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link active" href="{% url 'scheduleadvisor:student' %}">Home</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:search' %}">Search Courses</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:cart' %}">Cart</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:schedules' %}">Schedules</a>
                    </li>
                </ul>
            </div>
            <span class="navbar-text px-5" >
                <a href="/logout">Logout</a>
            </span>
        </nav>
        

        <script type="text/javascript">
            //cookie for shopping cart in cart.js
            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getToken('csrftoken');
        </script>
    </head>

    <body>
        <div class="container w-75 bg-light mx-auto pt-3 px-3 py-3 mx-5 my-5 border">
            <h4 class="text-center">Shopping Cart</h4>
            <!-- outputting all of the courses -->
            {% if courses %}
                {% for course in courses %}
                    <div class="my-5 mx-3 py-2 px-2 bg-white border shadow-sm">
            
                    <div class="my-1">
                        <h5>
                            <b>{{ course }}</b>
                        </h5>
                        {% if course.title != "" and course.topic != "" %}
                            <div class="my-1"><b>{{course.title}} - {{course.topic}}</b></div>
                        {% else %}
                            {% if course.title != "" %}
                                <div class="my-1"><b>{{ course.title }}</b></div>
                            {% endif %}
                            {% if course.topic != "" %}
                                <div class="my-1"><b>{{ course.topic }}</b></div>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="my-1 "><b>Subject:</b> {{ course.subject_description }}</div>
                            <div class="my-1"><b>Career:</b> {{ course.acad_career_descr }}</div>
                            <div class="my-1"><b>Section Type:</b> {{ course.section_type }}</div>
                            <div class="my-1"><b>Instructors:</b> {{ course.instructors }}</div>
                        </div>
                        <div class="col">
                            <div class="my-1"><b>Meetings</b>: {{ course.days }} {{ course.start_time }}-{{ course.end_time }}</div>
                            <div class="my-1"><b>Classroom:</b> {{ course.classroom }}</div>
                            <div class="my-1"><b>Units:</b> {{ course.units }}</div>
                            <div class="my-1"><b>Enrollment Status:</b> {{ course.enrollment_status }} (Seats filled: {{course.enrollment_total}}/{{course.class_capacity}})</div>
                        </div>
                    </div>
                    <button data-course={{course.class_number}} data-action="delete_course" class="btn btn-danger update-cart my-2">Delete from Cart</button>
                    </div>
                {% endfor %}
            {% else %}
                <div class="text-center my-3">
                    <p>Your shopping cart is empty.</p>
                    <a class="btn btn-primary btn-sm" href="{% url 'scheduleadvisor:search' %}">Search for Courses</a>
                </div>
            {% endif %}
        </div>
        <!-- for the cart buttons -->
        <script type="text/javascript" src="{% static 'scheduleadvisor/js/cart.js' %}"></script>
    </body>
</html>

scheduleadvisor/templates/scheduleadvisor/notauthorized.html
<!DOCTYPE html>

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!--

Citations

redirecting code: https://stackoverflow.com/questions/27660467/how-to-do-2-continuous-redirect-in-django

-->

<link rel="stylesheet" href="{% static 'scheduleadvisor/style.css' %}">

<html>
    <body>
        <div class="container w-75 mx-auto my-5">
            <p>Not authorized to visit this page.</p>
            <p>Redirecting to home page...</p>
        </div>

    </body>
</html>

<script>
    window.setTimeout(function(){
      window.location.href = "/";
    }, 3000);
</script>

scheduleadvisor/templates/scheduleadvisor/studentindex.html
{% load static %}
{% load bootstrap5 %}
{% load socialaccount %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'scheduleadvisor/style.css' %}">
        <nav class="navbar navbar-expand-lg">
            <a class="px-4 navbar-brand">Schedule Advisor</a>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link active" href="{% url 'scheduleadvisor:student' %}">Home</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:search' %}">Search Courses</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:cart' %}">Cart</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-item nav-link" href="{% url 'scheduleadvisor:schedules' %}">Schedules</a>
                    </li>
                </ul>
            </div>
            <span class="navbar-text px-5" >
                <a href="/logout">Logout</a>
            </span>
        </nav>
    </head>
    <body class="">
        <div class="body-container">
            <div>
                <div class="container w-75 bg-light px-3 py-3 mx-auto my-5 border">
                    <h4 class="text-center">Student Profile</h4>
                    <div class="container w-75 bg-white shadow-sm px-3 py-3 my-3">
                        <p>Name: {{ student }} </p>
                        <p>Username: {{ student.username }}</p>
                        <p>Email: {{ student.email }}</p>
                        {% if no_advisor %}
                            <p>Advisor: None</p>
                        {% else %}
                            <p>Advisor: {{ student.advisor }} ({{student.advisor.email}})</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="container w-75 bg-light px-3 py-3 mx-auto my-2 border">
                <form action="{% url 'scheduleadvisor:clear_notifs' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-auto">
                            <h4>Notifications</h4>
                        </div>
                        <div class="col-auto">
                            <input class="btn btn-danger btn-sm" type="submit" value="Clear Notifications">
                        </div>
                    </div>
                </form>
                
                {% if notifications %}
                    {% for notif in notifications %}
                        <div class="container bg-white shadow-sm px-3 py-3 mx-3 my-3">
                            {{ notif }}
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="my-1">
                        You have no notifications.
                    </div>
                {% endif %}
            </div>
        </div>
    </body>
</html>